config/routes.rb
Trails::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, controllers: { registrations: 'registrations'}, path: '/',
               path_names: {  sign_in: 'sessions/new',
                              sign_out: 'sessions/destroy' }
  resources :authentications
  resources :users

  root :to => 'home#index'

end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read,   User, id: user.id
      can :update, User, id: user.id
      can :create, User
      cannot :index, User
    end

  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :uid

  validates :provider, presence: true
  validates :uid, presence: true

  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :imgur_id

  validates :imgur_id , presence: true

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :match_id, :user_id, :interested

  belongs_to :user
  has_one :complement, :class_name => Match, 
    :foreign_key => :match_id,

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :from, :text, :to

  belongs_to :sender, class_name: User, :foreign_key => :from
  belongs_to :receiver, class_name:User, :foreign_key => :to

  validates :text, presence: true

end

app/models/rated_images.rb
class RatedImages < ActiveRecord::Base
  belongs_to :image
  attr_accessible :status

  validates :status, :inclusion => 1..4,

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :messages_inbox, class_name: Message, :foreign_key => :to
  has_many :messages_outbox, class_name: Message, :foreign_key => :from

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :current_password

  attr_accessor :current_password

  has_many :authentications, dependent: :destroy
  has_many :roles, dependent: :destroy

  has_attached_file :profile_picture,
                      styles: { medium: '300x300#', thumb: '100x100#' },
                      default_url: '/missing-:style.png'

  def admin?
    roles.where(name: :admin).any?
  end

  # Helper for user creation via omniauth
  def apply_omniauth(omniauth)
    authentications.build(provider: omniauth['provider'], uid: omniauth['uid'])
  end

  # Override devise password_required if user is signing in via omniauth
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to new_user_session_path, alert: exception.message
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  
  def create
    omniauth = request.env['omniauth.auth']
    authentication = Authentication.find_by_provider_and_uid(
      omniauth[:provider], omniauth[:uid])
    if authentication
      flash[:notice] = t(:signed_in_successfully)
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create(
        provider: omniauth[:provider], uid: omniauth[:uid])
      flash[:notice] = t(:authentication_successfull)
      redirect_to edit_user_url(current_user)
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = t(:signed_in_successfully)
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = t(:successfully_removed_authentication)
    redirect_to edit_user_url(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # This controller overrides the default devise registration controller
  # with our authentication logic.

  def create
    # Remove omniauth data from session after successful registration
    super
    session[:omniauth] = nil unless @user.new_record?
  end

  private

  # Override the devise build method for users using omniauth
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource :user

  # GET /users
  # GET /users.json
  def index
    @search = User.search(params[:q])
    @users = @search.result.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update

    @user = User.find(params[:id])

    # Password is not required unless updating password itself
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in @user, bypass: true
        format.html {
          redirect_to @user, notice: t(:updated,  model: User.model_name.human)
        }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/home/index.html.erb
<% if signed_in? %>
  <p>Content for signed in user goes here</p>
<% else %>
  <h2><%= t :welcome %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trails</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <li><%= link_to t(:home), root_path %></li>
  <% if user_signed_in? %>
    <li><%= t(:signed_in_as) %> <strong><%= current_user.email %></strong>.</li>
    <li><%= link_to t(:edit_profile), edit_user_path(current_user) %></li>
    <li><%= link_to t(:sign_out), destroy_user_session_path,
                    method: :delete %></li>
  <% else %>
    <li><%= link_to t(:sign_up), new_user_registration_path %></li>
    <li><%= link_to t(:sign_in), new_user_session_path %></li>
  <% end %>
  </ul>
</nav>

<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

<footer>
  <p>
    © <%= Time.now.year %> <%= t(:copyright) %> |
    Running in <%= Rails.env %> mode
    <% if Rails.env == 'production' or Rails.env == 'certification'%>
      Version 0.0.0
    <% end %>
  </p>
</footer>

<script>
  yepnope({
    // test : Modernizr.inputtypes.range,
    // nope : ["<%# asset_path('fd-slider/css/fd-slider.css') %>",
    //         "<%# asset_path('fd-slider/js/fd-slider.js') %>"]
  });
</script>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div>
      <h2>
        <%= pluralize(@user.errors.count, 'error') %>
        prohibited this user from being saved:
      </h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div>
    <%= image_tag @user.profile_picture.url(:thumb) %><br />
    <%= f.label :profile_picture %><br />
    <%= f.file_field :profile_picture %>
  </div>

  <div><%= f.label :password %>
    <i>(<%= t(:leave_blank_if_changing) %>)</i>
    <br/>
    <%= f.password_field :password, autocomplete: :off %>
  </div>

  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %></div>

  <div>
    <%= f.label :current_password %>
    <i>(<%= t(:if_you_are_changing) %>)</i>
    <br/>
    <%= f.password_field :current_password %>
  </div>

  <div><%= f.submit t(:update) %></div>
<% end %>


<% if @user.authentications %>
  <% unless @user.authentications.empty? %>
    <table>
      <caption><%= t(:you_can_sign_in_with_these_accounts) %></caption>
      <thead>
      <th><%= t('activerecord.attributes.authentication.provider') %></th>
      <th>ID</th><th></th></thead>
      <tbody>
      <% for authentication in @user.authentications %>
        <tr>
          <td><%= authentication.provider.titleize %></td>
          <td><%= authentication.uid %></td>
          <td><%= link_to t(:delete), authentication,
                          data: { confirm: t(:are_you_sure) },
                          method: :delete %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
  <p><strong><%= t(:add_another_service) %></strong></p>
<% else %>
  <p><strong><%= t(:sign_in_with_a_service) %></strong></p>
<% end %>

<ul>
  <li><%= link_to t(:sign_in_twitter), '/auth/twitter' %></li>
  <li><%= link_to t(:sign_in_facebook), '/auth/facebook' %></li>
</ul>

<h3><%= t(:cancel_my_account) %></h3>

<p><%= link_to t(:cancel_my_account), registration_path(@user),
               data: { confirm: t(:are_you_sure) },
               method: :delete %>.</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= search_form_for @search do |f| %>
  <div>
    <%= f.label :email_cont, t(:email) %>
    <%= f.text_field :email_cont %>
  </div>
  <div>
    <%= f.label :created_at_gteq, t(:created_between) %>
    <%= f.date_select :created_at_gteq, {include_blank: true, default: nil} %>
    <%= f.label :created_at_lteq, t(:and) %>
    <%= f.date_select :created_at_lteq, {include_blank: true, default: nil}  %>
  </div>
  <%= f.submit t(:search) %>
<% end %>

<%= paginate @users %>

<table>
  <tr>
    <th><%= sort_link(@search, :email) %></th>
    <th><%= sort_link(@search, :created_at) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.created_at.strftime("%m/%d/%y") %></td>
    <td><%= link_to t(:show), user %></td>
    <td><%= link_to t(:edit), edit_user_path(user) %></td>
    <td><%= link_to t(:delete), user, method: :delete,
                    data: { confirm: t(:are_you_sure) } %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>